{% set python_min = "3.10" %}
{% set name = "aws-cdk.cloud-assembly-schema" %}
{% set version = "48.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws_cdk_cloud_assembly_schema-{{ version }}.tar.gz
  sha256: c2c3836d5b1b5655a71226b8f6e1339b6db5f36e9c6533b8e572658d20676d9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - python-jsii >=1.114.1,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<4.3.0

test:
  imports:
    - aws_cdk.cloud_assembly_schema
    - aws_cdk.cloud_assembly_schema._jsii
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: Cloud Assembly Schema
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0 AND BSD-4-Clause
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
