schema_version: 1

context:
  version: "54.21.0"

package:
  name: aws-cdk.cloud-assembly-schema
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/aws-cdk.cloud-assembly-schema/aws_cdk_cloud_assembly_schema-${{ version }}.tar.gz
  sha256: bd66b07ab1a1570801219a3ad3e438a6853db284771cff7aa5e18935b2b3dd0c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=75.3.2
    - python-build >=1.5.0,<1.6.dev0
    - pip
  run:
    - python >=${{ python_min }}
    - python-jsii >=1.139.0,<2.0.0
    - publication >=0.0.3
tests:
  - python:
      imports:
        - aws_cdk.cloud_assembly_schema
        - aws_cdk.cloud_assembly_schema._jsii
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Schema for the protocol between CDK framework and CDK CLI
  license: Apache-2.0 AND MIT
  license_file:
    - NOTICE
    - LICENSE
  homepage: https://github.com/aws/aws-cdk
  repository: https://github.com/aws/aws-cdk-cli

extra:
  recipe-maintainers:
    - ocefpaf
